package dcdmod.Actions;

public class DecadeAnimationAction {
	
	public static String [] JSON = {
    		"",
			"img/char/DCD_Animation/decade/decade_normal.json",//1
			"img/char/DCD_Animation/decade/decade_henshin.json",//2
			"img/char/DCD_Animation/decade/decade_victory.json",//3
			"img/char/DCD_Animation/kuuga/kuuga_normal.json",//4
			"img/char/DCD_Animation/kuuga/kuuga_dcdtokuuga.json",//5
			"img/char/DCD_Animation/kuuga/kuuga_backtodcd.json",//6
			"img/char/DCD_Animation/kuuga/kuuga_Dragon.json",//7
			"img/char/DCD_Animation/kuuga/kuuga_Pegasus.json",//8
			"img/char/DCD_Animation/kuuga/kuuga_Titan.json",//9
			"img/char/DCD_Animation/kuuga/kuuga_allformbacktodcd.json",//10
			"img/char/DCD_Animation/agito/agito_backtodcd.json",//11
			"img/char/DCD_Animation/agito/agito_dcdtoagito.json",//12
			"img/char/DCD_Animation/agito/agito_flame.json",//13
			"img/char/DCD_Animation/agito/agito_normal.json",//14
			"img/char/DCD_Animation/agito/agito_storm.json",//15
			"img/char/DCD_Animation/agito/agito_normal_p.json",//16
			"img/char/DCD_Animation/agito/agito_normal_t.json",//17
			"img/char/DCD_Animation/agito/agito_normal_tp.json",//18
			"img/char/DCD_Animation/agito/agito_power_t.json",//19
			"img/char/DCD_Animation/agito/agito_power.json",//20
			"img/char/DCD_Animation/agito/agito_trinity.json",//21
			"img/char/DCD_Animation/ryuki/ryuki_attack.json",//22
			"img/char/DCD_Animation/ryuki/ryuki_backtodcd.json",//23
			"img/char/DCD_Animation/ryuki/ryuki_defend.json",//24
			"img/char/DCD_Animation/ryuki/ryuki_guard.json",//25
			"img/char/DCD_Animation/ryuki/ryuki_guardattack.json",//26
			"img/char/DCD_Animation/ryuki/ryuki_guardstrike.json",//27
			"img/char/DCD_Animation/ryuki/ryuki_henshin.json",//28
			"img/char/DCD_Animation/ryuki/ryuki_henshintonormal.json",//29
			"img/char/DCD_Animation/ryuki/ryuki_normal.json",//30
			"img/char/DCD_Animation/ryuki/ryuki_strike.json",//31
			"img/char/DCD_Animation/ryuki/ryuki_strikeattack.json",//32
			"img/char/DCD_Animation/faiz/faiz_FAR1.json",//33
			"img/char/DCD_Animation/faiz/faiz_normal.json",//34
			"img/char/DCD_Animation/faiz/faiz_henshin.json",//35
			"img/char/DCD_Animation/faiz/faiz_FAR0.json",//36
			"img/char/DCD_Animation/faiz/faiz_backtodcd.json",//37
			"img/char/DCD_Animation/faiz/faiz_gunattack.json",//38
			"img/char/DCD_Animation/faiz_Axel/Axel_henshin.json",//39
			"img/char/DCD_Animation/faiz_Axel/Axel_normal.json",//40
			"img/char/DCD_Animation/faiz_Axel/Axel_backtofaiz.json",//41
			"img/char/DCD_Animation/faiz_Axel/faiz_Axel_attack.json",//42
			"img/char/DCD_Animation/decade/decade_kamenride_kamenride.json",//43
			"img/char/DCD_Animation/decade/decade_kamenride_timer.json",//44
			"img/char/DCD_Animation/blade/blade_normal.json",//45
			"img/char/DCD_Animation/blade/jackform_normal.json",//46
			"img/char/DCD_Animation/blade/blade_backtodcd.json",//47
			"img/char/DCD_Animation/blade/jack_henshin1.json",//48
			"img/char/DCD_Animation/hibiki/hibiki_normal.json",//49
			"img/char/DCD_Animation/hibiki/hibiki_backtodcd.json",//50
			"img/char/DCD_Animation/hibiki/hibiki_taikoprepare.json",//51
			"img/char/DCD_Animation/hibiki/hibiki_taikoprepare2_prepare.json",//52
			"img/char/DCD_Animation/hibiki/hibiki_taikoprepare2_stop.json",//53
			"img/char/DCD_Animation/hibiki/hibiki_kurenai_henshin0.json",//54
			"img/char/DCD_Animation/hibiki/hibiki_kurenai_normal.json",//55
			"img/char/DCD_Animation/hibiki/hibiki_attack1.json",//56
			"img/char/DCD_Animation/hibiki/hibiki_attack2.json",//57
			"img/char/DCD_Animation/hibiki/hibiki_attack3.json",//58
			"img/char/DCD_Animation/kabuto/kabuto_henshin.json",//59
			"img/char/DCD_Animation/kabuto/kabuto_normal.json",//60
			"img/char/DCD_Animation/kabuto/kamenform_normal.json",//61
			"img/char/DCD_Animation/kabuto/kamenriderswitch_tokamenform.json",//62
			"img/char/DCD_Animation/kabuto/kamenriderswitch_toriderform.json",//63
			"img/char/DCD_Animation/kabuto/kabuto_backtodcd.json",//64
			"img/char/DCD_Animation/deno/deno_backtodcd.json",//65
			"img/char/DCD_Animation/deno/deno_normal.json",//66
			"img/char/DCD_Animation/deno/deno_henshin.json",//67
			"img/char/DCD_Animation/deno/deno_bokuni_tsurarete_miru.json",//68
			"img/char/DCD_Animation/deno/deno_kotaewa_kiite_nai.json",//69
			"img/char/DCD_Animation/deno/deno_nakerude.json"//70
    		};
	
	public static String [] ATLAS = {
			"",//0
			"img/char/DCD_Animation/decade/decade_normal.atlas",//1
			"img/char/DCD_Animation/decade/decade_henshin.atlas",//2
			"img/char/DCD_Animation/decade/decade_victory.atlas",//3
			"img/char/DCD_Animation/kuuga/kuuga_normal.atlas",//4
			"img/char/DCD_Animation/kuuga/kuuga_dcdtokuuga.atlas",//5
			"img/char/DCD_Animation/kuuga/kuuga_backtodcd.atlas",//6
			"img/char/DCD_Animation/kuuga/kuuga_Dragon.atlas",//7
			"img/char/DCD_Animation/kuuga/kuuga_Pegasus.atlas",//8
			"img/char/DCD_Animation/kuuga/kuuga_Titan.atlas",//9
			"img/char/DCD_Animation/kuuga/kuuga_allformbacktodcd.atlas",//10
			"img/char/DCD_Animation/agito/agito_backtodcd.atlas",//11
			"img/char/DCD_Animation/agito/agito_dcdtoagito.atlas",//12
			"img/char/DCD_Animation/agito/agito_flame.atlas",//13
			"img/char/DCD_Animation/agito/agito_normal.atlas",//14
			"img/char/DCD_Animation/agito/agito_storm.atlas",//15
			"img/char/DCD_Animation/agito/agito_normal_p.atlas",//16
			"img/char/DCD_Animation/agito/agito_normal_t.atlas",//17
			"img/char/DCD_Animation/agito/agito_normal_tp.atlas",//18
			"img/char/DCD_Animation/agito/agito_power_t.atlas",//19
			"img/char/DCD_Animation/agito/agito_power.atlas",//20
			"img/char/DCD_Animation/agito/agito_trinity.atlas",//21
			"img/char/DCD_Animation/ryuki/ryuki_attack.atlas",//22
			"img/char/DCD_Animation/ryuki/ryuki_backtodcd.atlas",//23
			"img/char/DCD_Animation/ryuki/ryuki_defend.atlas",//24
			"img/char/DCD_Animation/ryuki/ryuki_guard.atlas",//25
			"img/char/DCD_Animation/ryuki/ryuki_guardattack.atlas",//26
			"img/char/DCD_Animation/ryuki/ryuki_guardstrike.atlas",//27
			"img/char/DCD_Animation/ryuki/ryuki_henshin.atlas",//28
			"img/char/DCD_Animation/ryuki/ryuki_henshintonormal.atlas",//29
			"img/char/DCD_Animation/ryuki/ryuki_normal.atlas",//30
			"img/char/DCD_Animation/ryuki/ryuki_strike.atlas",//31
			"img/char/DCD_Animation/ryuki/ryuki_strikeattack.atlas",//32
			"img/char/DCD_Animation/faiz/faiz_FAR1.atlas",//33
			"img/char/DCD_Animation/faiz/faiz_normal.atlas",//34
			"img/char/DCD_Animation/faiz/faiz_henshin.atlas",//35
			"img/char/DCD_Animation/faiz/faiz_FAR0.atlas",//36
			"img/char/DCD_Animation/faiz/faiz_backtodcd.atlas",//37
			"img/char/DCD_Animation/faiz/faiz_gunattack.atlas",//38
			"img/char/DCD_Animation/faiz_Axel/Axel_henshin.atlas",//39
			"img/char/DCD_Animation/faiz_Axel/Axel_normal.atlas",//40
			"img/char/DCD_Animation/faiz_Axel/Axel_backtofaiz.atlas",//41
			"img/char/DCD_Animation/faiz_Axel/faiz_Axel_attack.atlas",//42
			"img/char/DCD_Animation/decade/decade_kamenride.atlas",//43
			"img/char/DCD_Animation/decade/decade_kamenride.atlas",//44
			"img/char/DCD_Animation/blade/blade_normal.atlas",//45
			"img/char/DCD_Animation/blade/jackform_normal.atlas",//46
			"img/char/DCD_Animation/blade/blade_backtodcd.atlas",//47
			"img/char/DCD_Animation/blade/jack_henshin1.atlas",//48
			"img/char/DCD_Animation/hibiki/hibiki_normal.atlas",//49
			"img/char/DCD_Animation/hibiki/hibiki_backtodcd.atlas",//50
			"img/char/DCD_Animation/hibiki/hibiki_taikoprepare.atlas",//51
			"img/char/DCD_Animation/hibiki/hibiki_taikoprepare2.atlas",//52
			"img/char/DCD_Animation/hibiki/hibiki_taikoprepare2.atlas",//53
			"img/char/DCD_Animation/hibiki/hibiki_kurenai_henshin0.atlas",//54
			"img/char/DCD_Animation/hibiki/hibiki_kurenai_normal.atlas",//55
			"img/char/DCD_Animation/hibiki/hibiki_attack1.atlas",//56
			"img/char/DCD_Animation/hibiki/hibiki_attack2.atlas",//57
			"img/char/DCD_Animation/hibiki/hibiki_attack3.atlas",//58
			"img/char/DCD_Animation/kabuto/kabuto_henshin.atlas",//59
			"img/char/DCD_Animation/kabuto/kabuto_normal.atlas",//60
			"img/char/DCD_Animation/kabuto/kamenform_normal.atlas",//61
			"img/char/DCD_Animation/kabuto/kamenriderswitch.atlas",//62
			"img/char/DCD_Animation/kabuto/kamenriderswitch.atlas",//63
			"img/char/DCD_Animation/kabuto/kabuto_backtodcd.atlas",//64
			"img/char/DCD_Animation/deno/deno_backtodcd.atlas",//65
			"img/char/DCD_Animation/deno/deno_normal.atlas",//66
			"img/char/DCD_Animation/deno/deno_henshin.atlas",//67
			"img/char/DCD_Animation/deno/deno_bokuni_tsurarete_miru.atlas",//68
			"img/char/DCD_Animation/deno/deno_kotaewa_kiite_nai.atlas",//69
			"img/char/DCD_Animation/deno/deno_nakerude.atlas"//70
    		};
	
	public static String [] NAME = {
			"",//0
			"normal",//1
			"hensin",//2
			"victory",//3
			"normal",//4
			"dcdtokuuga",//5
    		"backtodcd",//6
    		"Dragon",//7
    		"Pegasus",//8
    		"Titan",//9
    		"allformbacktodcd",//10
    		"backtodcd",//11
    		"dcdtoagito",//12
    		"flame",//13
    		"normal",//14
    		"storm",//15
    		"normal_p",//16
    		"normal_t",//17
    		"normal_tp",//18
    		"power_t",//19
    		"power",//20
    		"trinity",//21
    		"attack",//22
    		"backtodcd",//23
    		"defend",//24
    		"guard",//25
    		"guardattack",//26
    		"guardstrike",//27
    		"hensin",//28
    		"hensintonormal",//29
    		"normal",//30
    		"strike",//31
    		"strikeattack",//32
    		"FAR1",//33
    		"normal",//34
    		"hensin",//35
    		"FAR0",//36
    		"backtodcd",//37
    		"gunattack",//38
    		"henshin",//39
    		"normal",//40
    		"backtofaiz",//41
    		"Axel_attack",//42
    		"kamenride",//43
    		"timer",//44
    		"normal",//45
    		"normal",//46
    		"backtodcd",//47
    		"henshin",//48
    		"normal",//49
    		"backtodcd",//50
    		"prepare",//51
    		"prepare",//52
    		"stop",//53
    		"henshin",//54
    		"normal",//55
    		"attack",//56
    		"attack",//57
    		"attack",//58
    		"henshin",//59
    		"normal",//60
    		"normal",//61
    		"tokamenform",//62
    		"toriderform",//63
    		"backtodcd",//64
			"backtodcd",//65
			"normal",//66
			"henshin",//67
			"bokunitsuraretemiru",//68
			"kotaewa_kiite_nai",//69
			"nakerude"//70
	};
    
}

